import type { Metadata } from "next";

//overide root layout metadat
// export const metadata: Metadata = {
//   title: "dashboard Layout",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
 title:{
  // absolute:'',// can't change 
  default:'Default title ',// fallback when title is not specified in child route
  template:'%s | with Template' // template is included along woth child title
}
}

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <> 
    <header>dashboard Header</header>
        {children}
      <footer>dashboard Footer</footer>
  </>
      );
}
